org.gradle.jvmargs = -Xmx6G
org.gradle.java.installations.auto-download=false
# JDK 工具链位置（本机）：Gradle 需要 JDK 17 编译，ModDevGradle 需要 JDK 21 运行 NeoForm 反编译
org.gradle.java.installations.paths=D:/Software/Java/zulu17.68.203,D:/Software/Java/zulu21.36.17
org.gradle.parallel = true
org.gradle.caching = true

# Mod Info
mod_id = gtceu
mod_name = GregTech
mod_version = 7.5.3
mod_description = GregTech CE Unofficial, ported from 1.12.2
mod_license = LGPL-3.0 license
mod_url = https://github.com/GregTechCEu/GregTech-Modern/
mod_issue_tracker = https://github.com/GregTechCEu/GregTech-Modern/issues/
maven_group = com.gregtechceu.gtceu
